from tinydb import TinyDB, Query, where

lnks = [
    ["short.st", "http://gestyy.com/eq0dcr"],
    ["short.st", "http://gestyy.com/eq0dnd"],
    ["short.st", "http://gestyy.com/eq0dn1"],
    ["short.st", "http://gestyy.com/eq0dmh"],
    ["short.st", "http://gestyy.com/eq0dQb"],
    ["short.st", "http://gestyy.com/eq0dWs"],
    ["short.st", "http://gestyy.com/eq0dEp"],
    ["short.st", "http://gestyy.com/eq0dEL"],
    ["short.st", "http://gestyy.com/eq0dRJ"],
    ["short.st", "http://gestyy.com/eq0dTT"],
    ["short.st", "http://gestyy.com/eq0dYr"],
    ["short.st", "http://gestyy.com/eq0dYK"],
    ["short.st", "http://gestyy.com/eq0dUM"],
    ["short.st", "http://gestyy.com/eq0dIO"],
    ["short.st", "http://gestyy.com/eq0dOk"],
    ["short.st", "http://gestyy.com/eq0dOS"],
    ["short.st", "http://gestyy.com/eq0dPm"],
    ["short.st", "http://gestyy.com/eq0dAl"],
    ["short.st", "http://gestyy.com/eq0dA7"],
    ["short.st", "http://gestyy.com/eq0dSc"],
    ["short.st", "http://gestyy.com/eq0dS5"],
    ["short.st", "http://gestyy.com/eq0dFJ"],
    ["short.st", "http://gestyy.com/eq0dF1"],
    ["short.st", "http://gestyy.com/eq0dGZ"],
    ["short.st", "http://gestyy.com/eq0dHl"],
    ["short.st", "http://gestyy.com/eq0dHI"],
    ["short.st", "http://gestyy.com/eq0haV"],
    ["short.st", "http://gestyy.com/eq0hss"],
    ["short.st", "http://gestyy.com/eq0hsY"],
    ["short.st", "http://gestyy.com/eq0hdt"],
    ["short.st", "http://gestyy.com/eq0hd8"],
    ["short.st", "http://gestyy.com/eq0hfW"],
    ["short.st", "http://gestyy.com/eq0hgq"],
    ["short.st", "http://gestyy.com/eq0hgT"],
    ["short.st", "http://gestyy.com/eq0hhE"],
    ["short.st", "http://gestyy.com/eq0hh2"],
    ["short.st", "http://gestyy.com/eq0hjs"],
    ["short.st", "http://gestyy.com/eq0hjY"],
    ["short.st", "http://gestyy.com/eq0hj5"],
    ["short.st", "http://gestyy.com/eq0hk0"],
    ["short.st", "http://gestyy.com/eq0hk3"],
    ["short.st", "http://gestyy.com/eq0hle"],
    ["short.st", "http://gestyy.com/eq0hli"],
    ["short.st", "http://gestyy.com/eq0hlk"],
    ["short.st", "http://gestyy.com/eq0hlJ"],
    ["short.st", "http://gestyy.com/eq0hzq"],
    ["short.st", "http://gestyy.com/eq0hzP"],
    ["short.st", "http://gestyy.com/eq0hz9"],
    ["short.st", "http://gestyy.com/eq0hcw"],
]

lnkstbl = TinyDB('db/bot.json').table('links')
lnkstbl.truncate()
for lnk in lnks:

    lnkstbl.insert({'type': lnk[0], 'url': lnk[1]})
